# Zola configuration, see: https://www.getzola.org/documentation/getting-started/configuration
base_url = "https://stikić.com"
title = "studio opaque"
description = "personal webzone of sandro stikić"
theme = "terminimal"
default_language = "en"
compile_sass = true
# Enable atom feed generation.
generate_feeds = true
feed_filenames = ["atom.xml"]
taxonomies = [{ name = "tags" }]
build_search_index = true

[markdown]
highlight_code = true
highlight_theme = "monokai-pro-terminimal"
extra_syntaxes_and_themes = ["themes/terminimal/highlight_themes"]
# Set all external links to open in a new window/tab.
external_links_target_blank = true
# Use github style footnotes, with backreferences at the bottom of pages.
bottom_footnotes = true

# Theme settings, see: https://github.com/pawroman/zola-theme-terminimal?tab=readme-ov-file#configuration
[extra]
blog_path = "blog"
source_url = "https://github.com/opeik/website"
version_url = "https://github.com/opeik/website/tree"
mastodon_url = "https://hachyderm.io/@opeik"
font = "iosevka"
accent_color = "purple"
background_color = "purple"
logo_text = "studio opaque"
author = "Sandro Stikić"
favicon = "/favicon.png"
favicon_mimetype = "image/png"
post_view_navigation_prompt = "Read more?"
# Method used for generating page titles, `{page_title} | {blog_title}`.
page_titles = "combined"
# Path for fallback embed preview image (1200x628), relative to `/static`.
default_og_image = "favicon.png"

menu_items = [
    { name = "blog", url = "$BASE_URL" },
    { name = "tags", url = "$BASE_URL/tags" },
    { name = "archive", url = "$BASE_URL/archive" },
    { name = "wtf-8", url = "$BASE_URL/wtf-8" },
    { name = "about", url = "$BASE_URL/about" },
]

[extra.utterances]
enabled = true
repo = "opeik/website"
post_map = "pathname"
label = "utterances"
theme = "github-dark-orange"

[search]
index_format = "elasticlunr_json"
