# Zola configuration, see: https://www.getzola.org/documentation/getting-started/configuration
base_url = "https://stikić.com"
title = "Sandro Stikić"
theme = "terminimal"
default_language = "en"
compile_sass = true
generate_feed = true
taxonomies = [{ name = "tags" }]

[markdown]
highlight_code = true
# highlight_theme = "base16-ocean-dark"

# Theme settings, see: https://github.com/pawroman/zola-theme-terminimal?tab=readme-ov-file#configuration
[extra]
blog_path = "blog"
source_url = "https://github.com/opeik/website"
accent_color = "pink"
background_color = "pink"
logo_text = "Sandro Stikić"
author = "Sandro Stikić"
favicon = "/favicon.png"
favicon_mimetype = "image/png"
post_view_navigation_prompt = "Read more?"
menu_items = [
    { name = "blog", url = "$BASE_URL" },
    { name = "tags", url = "$BASE_URL/tags" },
    { name = "archive", url = "$BASE_URL/archive" },
    { name = "about", url = "$BASE_URL/about" },
]

[extra.utterances]
enabled = true
repo = "opeik/website"
post_map = "pathname"
label = "utterances"
theme = "github-dark-orange"
