name: Deploy to GitHub Pages

on:
  push:
    branches: [main]
    paths: [config.toml, flake.*, content, static, templates]
  workflow_dispatch:

permissions:
  contents: read
  pages: write
  id-token: write

concurrency:
  group: pages
  cancel-in-progress: true

jobs:
  deploy:
    runs-on: ubuntu-latest
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Install Nix
        uses: DeterminateSystems/nix-installer-action@main

      - name: Setup Nix cache
        uses: DeterminateSystems/magic-nix-cache-action@main

      - name: Build website
        run: |
          nix build --print-build-logs
          cp --recursive --dereference --no-preserve=mode,ownership result public

      - name: Setup GitHub Pages
        uses: actions/configure-pages@v1

      - name: Upload website content
        uses: actions/upload-pages-artifact@v1
        with:
          path: public

      - name: Deploy website
        id: deployment
        uses: actions/deploy-pages@v1
